version: '1.0.{build}'
image: Visual Studio 2017
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore --verbosity m
build_script:
  - cmd: dotnet build
clone_depth: 1
test_script:
  - cmd: cd test\\VaultSharp.UnitTests && dotnet test
deploy: off